#!/bin/bash
# Mock cursor CLI for pipeline orchestration testing.
#
# Simulates two behaviors:
#   1. create-chat → returns deterministic UUID
#   2. --print --resume <id> → reads stdin, writes call log,
#      and either writes next-prompt.md (commander) or outputs [!SUCCESS] (executor)
#
# State is kept in MOCK_STATE_DIR (cleaned per test run).
# MOCK_NEXT_PROMPT must be set by the test runner to the expected next-prompt.md path.

set -euo pipefail

MOCK_STATE_DIR="${MOCK_STATE_DIR:?MOCK_STATE_DIR must be set}"
MOCK_NEXT_PROMPT="${MOCK_NEXT_PROMPT:?MOCK_NEXT_PROMPT must be set}"

CALL_LOG="${MOCK_STATE_DIR}/call-log.txt"
COUNTER_FILE="${MOCK_STATE_DIR}/counter"
COMMANDER_ID_FILE="${MOCK_STATE_DIR}/commander-id"

mkdir -p "$MOCK_STATE_DIR"

next_counter() {
    local c
    c=$(cat "$COUNTER_FILE" 2>/dev/null || echo "0")
    echo $(( c + 1 )) > "$COUNTER_FILE"
    echo "$c"
}

subcmd="${1:-}"
shift || true

case "$subcmd" in
    agent)
        action="${1:-}"

        if [[ "$action" == "create-chat" ]]; then
            local_counter=$(next_counter)
            fake_id=$(printf "00000000-0000-0000-0000-%012d" "$local_counter")
            echo "CREATE_CHAT → ${fake_id}" >> "$CALL_LOG"
            echo "$fake_id"
            exit 0
        fi

        # Parse --print --resume <id>
        chat_id=""
        for arg in "$@"; do
            if [[ "${prev_arg:-}" == "--resume" ]]; then
                chat_id="$arg"
            fi
            prev_arg="$arg"
        done

        stdin_content=$(cat)
        stdin_first_line=$(echo "$stdin_content" | head -1)

        commander_id=$(cat "$COMMANDER_ID_FILE" 2>/dev/null || echo "")

        if echo "$stdin_content" | grep -q "指挥官 AI"; then
            # Commander init message — save ID, respond "就绪"
            echo "$chat_id" > "$COMMANDER_ID_FILE"
            echo "COMMANDER_INIT → ${chat_id}" >> "$CALL_LOG"
            echo "就绪"

        elif [[ "$chat_id" == "$commander_id" ]]; then
            # Commander message — extract step reference, write next-prompt.md
            template_ref=$(echo "$stdin_content" | grep -oE 'step-[a-z0-9-]+\.md' | head -1 || echo "unknown")
            module_info=$(echo "$stdin_content" | grep -oE 'module_id=[^,]+, module_name=[^,]+, module_suffix=[a-z]' || echo "")

            echo "COMMANDER_ASK → template=${template_ref} ${module_info}" >> "$CALL_LOG"

            # Write a minimal valid prompt (simulates 001's file write side-effect)
            cat > "$MOCK_NEXT_PROMPT" <<PROMPT_EOF
# Mock prompt generated by 001
# Template: ${template_ref}
# ${module_info}
This is a mock prompt for orchestration testing.
PROMPT_EOF

        else
            # Executor — output fake [!SUCCESS] block
            echo "EXECUTOR_RUN → ${chat_id} stdin_line1='${stdin_first_line}'" >> "$CALL_LOG"
            cat <<SUCCESS_EOF
[Mock Executor] Processing prompt...

> [!SUCCESS] Mock execution complete
> - LEGACY_STATUS: HAS_DOCS
> - LEGACY_COUNT=5
> - 扫描范围: mock
> - EOF 状态: OK
SUCCESS_EOF
        fi
        ;;
    --version)
        echo "mock-cursor 1.0.0"
        ;;
    *)
        echo "mock-cursor: unhandled command: $subcmd $*" >&2
        exit 1
        ;;
esac
